-- Telegram accounts linked to Metriq Flow users
CREATE TABLE IF NOT EXISTS telegram_users (
    id                SERIAL PRIMARY KEY,
    user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    telegram_id       BIGINT  NOT NULL UNIQUE,
    telegram_username VARCHAR(255),
    first_name        VARCHAR(255),
    linked_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Short-lived tokens for account linking (generated by web app)
CREATE TABLE IF NOT EXISTS telegram_link_tokens (
    id         SERIAL PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Channels where bot is admin and collecting data
CREATE TABLE IF NOT EXISTS telegram_channels (
    id           SERIAL PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel_id   BIGINT  NOT NULL UNIQUE,
    title        VARCHAR(512),
    username     VARCHAR(255),
    member_count INTEGER,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    added_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Posts collected from tracked channels
CREATE TABLE IF NOT EXISTS telegram_posts (
    id              SERIAL PRIMARY KEY,
    channel_id      BIGINT  NOT NULL,
    message_id      INTEGER NOT NULL,
    text            TEXT,
    views           INTEGER NOT NULL DEFAULT 0,
    forwards        INTEGER NOT NULL DEFAULT 0,
    reactions_total INTEGER NOT NULL DEFAULT 0,
    has_media       BOOLEAN NOT NULL DEFAULT FALSE,
    posted_at       TIMESTAMPTZ,
    collected_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (channel_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_tg_users_telegram_id   ON telegram_users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_tg_channels_user_id    ON telegram_channels(user_id);
CREATE INDEX IF NOT EXISTS idx_tg_channels_channel_id ON telegram_channels(channel_id);
CREATE INDEX IF NOT EXISTS idx_tg_posts_channel_id    ON telegram_posts(channel_id);
CREATE INDEX IF NOT EXISTS idx_tg_posts_posted_at     ON telegram_posts(posted_at DESC);
